### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by abhi18av** [dmiller/clojure-clr-next#1]
Hi @dmiller

I'm quite interested in the ClojureCLR project and am looking forward to the clojureCLR-next. I've joined the G+ group, is there any other mailing list I could join?

Merry Christmas 😄

**Comment by dmiller** [comment]
I just answered your post on G+.

Most important mailing list is https://groups.google.com/forum/#!forum/clojure-clr

**Comment by abhi18av** [comment]
Sure, thanks! :+1:
