### ISSUE TITLE
F# for ClojureCLR-next , have you considered Fable?

### ISSUE THREAD

**Issue by abhi18av** [dmiller/clojure-clr-next#2]
Hi again @dmiller)

Hey, I read in the wiki that you're looking to implement the next version of clojureCLR in F# - this definitely makes me exited as apart from Haskell, this is one language with a `type-system` !

Anyway, have you seen the F# -> JS  [Fable trans-compiler](https://github.com/fable-compiler/Fable) ? I feel that the first major hiccup we can address is to provide a comfortable dev. environment and if we model our approach on the [Ionide project](http://ionide.io/) with and related projects within [github/ionide](https://github.com/ionide) org. we can keep the entire experience pretty simple.

Plus, we can target VSCode and Atom for ClojureCLR at the same time - the [F# compiler is now available in `coreCLR`](https://github.com/dotnet/netcorecli-fsc/wiki/FAQ).

Moving forward, what's your plan?

**Comment by dmiller** [comment]
There were three possibilities:  continue in C# (boring), try to do a full clojure-in-clojure implementation (too hard) and F# (I get to have some fun).  HOwever, I'm still getting my F# skills in shape.  Part of that is reading, part coding.  And I've been looking through the F# compiler --as you pointed out.    I have not look at the Fable trans-compiler -- thanks for pointing it out.  I'm adding it to my list.

The dev environment is an issue.  Even without clojure-clr-next, that could be worked on.  Ionide I've used a little, haven't looked at the code.  I agree with the thought that if it's good enough for the F# crowd, and simple, it will be a good model.  Do you have an interest in pursuing that side of things?

Feel free to contact me directly at dmiller2718 [at] gmail.com

**Comment by abhi18av** [comment]
Nice to hear back from you, so I'm moving the conversation to the mails :)
