### ISSUE TITLE
Shall we create a project/wiki here?

### ISSUE THREAD

**Issue by abhi18av** [dmiller/clojure-clr-next#3]
Hi @dmiller

So, I thought it might be a good idea if we create a project/wiki here outlining steps that you've planned so far - or the ones which are still being planned.

Might help gain momentum for `ClojureCLR`

**Comment by dmiller** [comment]
Already have multiple wiki pages describing thoughts so far.
Need to figure out how to use projects for this. (I haven't used them so far.)

**Comment by abhi18av** [comment]
Oh, no issues.

The `dotNET coreCLR` guys seem to be making good use of it.

[main projects page](https://github.com/dotnet/coreclr/projects) and [a sample project](https://github.com/dotnet/coreclr/projects/3)

Also, I think the Github people are still getting used to it but since it has been there in Gitlab, they make a much better use of it [Gitlab kanban board](https://gitlab.com/gitlab-org/gitlab-ce/boards)

**Comment by dmiller** [comment]
Thanks for the links.
I'll check them out.
Too busy to spend much hammock time on the design parameters until
Friday/Saturday.
